Application=Odisha Tourism
Environment=Staging
Base.URL=https://apptourlfr-stg.estpl.net/home
Testing.Type=AI-Assisted Manual Testing
Execution.Tool=Playwright MCP
Test.Framework=Playwright Test
Browser=Chromium
Operating.System=Windows
Tested.By=Prashanta Behera
Execution.Date=29-09-2026